version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todos_app_api:latest
    container_name: todos_api
    environment:
      - MONGO_USER=mongo
      - MONGO_PASSWORD=password
      - MONGO_IP=db
      - MONGO_PORT=27017
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo
    container_name: todos_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
